name: arrmate
description: "Companion app for Radarr and Sonarr"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  app_links: ^7.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_secure_storage: ^10.0.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^17.0.1
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
