name: arrmate
description: "Companion app for Radarr and Sonarr"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  app_links: ^7.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^17.0.1
  hive_ce_flutter: ^2.3.3
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  flutter_cache_manager: ^3.3.1
  riverpod_annotation: ^2.6.1
  flutter_local_notifications: ^18.0.0
  workmanager: ^0.9.0+3
  ota_update: ^7.1.0
  package_info_plus: ^9.0.0
  pub_semver: ^2.2.0
  logger: ^2.6.2
  device_info_plus: ^12.3.0
  path_provider: ^2.1.5
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_ce_generator: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground_inset: 20
